Set
Sets are used to store multiple items in a single variable.

Set is one of 4 built-in data types in Python used to store collections of data, the other 3 are List, Tuple, and Dictionary, all with different qualities and usage.

A set is a collection which is unordered, unchangeable*, and unindexed.

* Note: Set items are unchangeable, but you can remove items and add new items.

Sets are written with curly brackets. {}

SET ITEMS

Set items are unordered, unchangeable, and do not allow duplicate values.

-Unordered-

Unordered means that the items in a set do not have a defined order.


Set items can appear in a different order every time you use them, and cannot be referred to by index or key.

-Unchangeable-

Set items are unchangeable, meaning that we cannot change the items after the set has been created.


Once a set is created, you cannot change its items, but you can remove items and add new items.

In [ ]:
# duplicates will be ignore
#Note: The values True and 1 are considered the same value in sets, and are treated as duplicates:

thisset = {"apple", "banana", "cherry", "apple"}

print(thisset)


#True and 1 is considered the same value:

thisset = {"apple", "banana", "cherry", True, 1, 2}
print(thisset)

#False and 0 is considered the same value:

thisset = {"apple", "banana", "cherry", False, True, 0}
print(thisset)

#can contain all types of data 
set1 = {"abc", 34, True, 40, "male"}

#its type is set
myset = {"apple", "banana", "cherry"}
print(type(myset))

# set constructor/casting
thisset = set(("apple", "banana", "cherry")) # note the double round-brackets
print(thisset)

ACCESS A SET

In [ ]:
#LOOP THROUGH SET
thisset = {"apple", "banana", "cherry"}

for x in thisset:
  print(x)
  
#CHECK IF STH IS PRESENT
thisset = {"apple", "banana", "cherry"}

print("banana" in thisset)

#Check if STH is NOT present in the set:

thisset = {"apple", "banana", "cherry"}
print("banana" not in thisset)

ADD ITEMS

In [ ]:
#Once a set is created, you cannot change its items, but you can add new items.

#Add an item to a set, using the add() method:

thisset = {"apple", "banana", "cherry"}

thisset.add("orange")

print(thisset)

#Add elements from tropical into thisset:

thisset = {"apple", "banana", "cherry"}
tropical = {"pineapple", "mango", "papaya"}

thisset.update(tropical)

print(thisset)

#ADD ANY ITERABLE
#Add elements of a list to at set:

thisset = {"apple", "banana", "cherry"}
mylist = ["kiwi", "orange"]

thisset.update(mylist)

print(thisset)

REMOVE ITEMS

In [ ]:
#USING REMOVE()
#If the item to remove does not exist, remove() will raise an error.

thisset = {"apple", "banana", "cherry"}

thisset.remove("banana")

print(thisset)

#USING DISCARD()
#Remove "banana" by using the discard() method:

thisset = {"apple", "banana", "cherry"}

thisset.discard("banana")

print(thisset)


#USING POP
#Remove a random item by using the pop() method:
#Sets are unordered, so when using the pop() method, you do not know which item that gets removed.
thisset = {"apple", "banana", "cherry"}

x = thisset.pop()

print(x)

print(thisset)

#USING CLEAR()
#The clear() method empties the set:

thisset = {"apple", "banana", "cherry"}

thisset.clear()

print(thisset)

#USING DEL
#The del keyword will delete the set completely:

thisset = {"apple", "banana", "cherry"}

del thisset

#print(thisset)

LOOP ITEMS

In [ ]:
#Loop through the set, and print the values:

thisset = {"apple", "banana", "cherry"}

for x in thisset:
  print(x)

JOIN SETS

In [ ]:
#There are several ways to join two or more sets in Python.

The union() and update() methods joins all items from both sets.

The intersection() method keeps ONLY the duplicates.

The difference() method keeps the items from the first set that are not in the other set(s).

The symmetric_difference() method keeps all items EXCEPT the duplicates.

In [ ]:
#UNION() 
#Join set1 and set2 into a new set:

set1 = {"a", "b", "c"}
set2 = {1, 2, 3}

set3 = set1.union(set2)
print(set3)

#Use | to join two sets:

set1 = {"a", "b", "c"}
set2 = {1, 2, 3}

set3 = set1 | set2
print(set3)

#Join multiple sets with the union() method:

set1 = {"a", "b", "c"}
set2 = {1, 2, 3}
set3 = {"John", "Elena"}
set4 = {"apple", "bananas", "cherry"}

myset = set1.union(set2, set3, set4)
print(myset)

#USING |

set1 = {"a", "b", "c"}
set2 = {1, 2, 3}
set3 = {"John", "Elena"}
set4 = {"apple", "bananas", "cherry"}

myset = set1 | set2 | set3 |set4
print(myset)

#Join a set with a tuple:

x = {"a", "b", "c"}
y = (1, 2, 3)

z = x.union(y)
print(z)

#The  | operator only allows you to join sets with sets,
# and not with other data types like you can with the  union() method.

In [24]:
#The update() method inserts all items from one set into another.

#The update() changes the original set, and does not return a new set.

#The update() method inserts the items in set2 into set1:

set1 = {"a", "b" , "c"}
set2 = {1, 2, 3}

set1.update(set2)
print(set1)

#Note: Both union() and update() will exclude any duplicate items.

{1, 2, 3, 'c', 'b', 'a'}

In [30]:
#INTERSECCION

#INTERSECTION()
#Keep ONLY the duplicates
#The intersection() method will return a new set, that only contains the items that are present in both sets.

#Join set1 and set2, but keep only the duplicates:

set1 = {"apple", "banana", "cherry"}
set2 = {"google", "microsoft", "apple"}

set3 = set1.intersection(set2)
print(set3)

#USING &
#You can use the & operator instead of the intersection() method, and you will get the same result.

set1 = {"apple", "banana", "cherry"}
set2 = {"google", "microsoft", "apple"}

set3 = set1 & set2
print(set3)
#Note: The & operator only allows you to join sets with sets,
# and not with other data types like you can with the intersection() method.


#INTERSECTION_UPDATE()
#The intersection_update() method will also keep ONLY the duplicates,
# but it will change the original set instead of returning a new set.
#Keep the items that exist in both set1, and set2:

set1 = {"apple", "banana", "cherry"}
set2 = {"google", "microsoft", "apple"}

set1.intersection_update(set2)

print(set1)

#The values True and 1 are considered the same value. The same goes for False and 0.
set1 = {"apple", 1,  "banana", 0, "cherry"}
set2 = {False, "google", 1, "apple", 2, True}

set3 = set1.intersection(set2)

print(set3)

{'apple'}
{'apple'}
{'apple'}
{False, 1, 'apple'}

In [37]:
#DIFFERENCE

#DIFFERENCE()
# The difference() method will return a new set that will
# contain only the items from the first set that are not
# present in the other set.

#Keep all items from set1 that are not in set2:

set1 = {"apple", "banana", "cherry"}
set2 = {"google", "microsoft", "apple"}

set3 = set1.difference(set2)

print(set3)

#USING -
#You can use the - operator instead of the difference() method, and you will get the same result.

#Use - to join two sets:

set1 = {"apple", "banana", "cherry"}
set2 = {"google", "microsoft", "apple"}

set3 = set1 - set2
print(set3)

#Note: The - operator only allows you to join sets with sets,
# and not with other data types like
# you can with the difference() method.


#USING DIFFERENCE_UPDATE()
# The difference_update() method
# will also keep the items from the first
# set that are not in the other set, but it will
# change the original set instead of returning a new set.

#Use the difference_update() method to keep the items that are not present in both sets:

set1 = {"apple", "banana", "cherry"}
set2 = {"google", "microsoft", "apple"}

set1.difference_update(set2)

print(set1)

{'cherry', 'banana'}
{'cherry', 'banana'}
{'banana', 'cherry'}

In [40]:
#SYMMETRIC DIFFERENCES

#The symmetric_difference() method will keep only the elements
# that are NOT present in both sets.

#Keep the items that are not present in both sets:

set1 = {"apple", "banana", "cherry"}
set2 = {"google", "microsoft", "apple"}

set3 = set1.symmetric_difference(set2)

print(set3)

#USING ^
#You can use the ^ operator instead of the symmetric_difference() method,
# and you will get the same result.

#Use ^ to join two sets:

set1 = {"apple", "banana", "cherry"}
set2 = {"google", "microsoft", "apple"}

set3 = set1 ^ set2
print(set3)


# Note: The ^ operator only allows you to join sets with sets,
# and not with other data types like you can with the symmetric_difference() method.



# #USING SIMMETRIC_DIFFERENCE_UPDATE()
# The symmetric_difference_update() method will also keep all but the duplicates,
# but it will change the original set instead of returning a new set.


#Use the symmetric_difference_update() method to keep
# the items that are not present in both sets:

set1 = {"apple", "banana", "cherry"}
set2 = {"google", "microsoft", "apple"}

set1.symmetric_difference_update(set2)

print(set1)

{'cherry', 'microsoft', 'google', 'banana'}
{'cherry', 'microsoft', 'google', 'banana'}
{'banana', 'cherry', 'microsoft', 'google'}

SET METHODS

In [ ]:
Method	Shortcut	Description
add()	 	#Adds an element to the set
clear()	 	#Removes all the elements from the set
copy()	 	#Returns a copy of the set
difference()	-	#Returns a set containing the difference between two or more sets
difference_update()	-=	#Removes the items in this set that are also included in another, specified set
discard()	 	#Remove the specified item
intersection()	&	#Returns a set, that is the intersection of two other sets
intersection_update()	&=	#Removes the items in this set that are not present in other, specified set(s)
isdisjoint()	 	#Returns whether two sets have a intersection or not
issubset()	<=	#Returns whether another set contains this set or not
issubset() 	<	#Returns whether all items in this set is present in other, specified set(s)
  
issuperset()	>=	#Returns whether this set contains another set or not
issuperset() 	>	#Returns whether all items in other, specified set(s) is present in this set
  
pop()	 	#Removes an element from the set
remove()	 	#Removes the specified element
symmetric_difference()	^	#Returns a set with the symmetric differences of two sets
symmetric_difference_update()	^=	#Inserts the symmetric differences from this set and another
union()	|	#Return a set containing the union of sets
update()	|=	#Update the set with the union of this set and others